remote_theme: pmarsceill/just-the-docs
title: Canada Moist Talkers
description: Talk Spit, Get Hits. Logo by @longhairQ
logo: https://raw.githubusercontent.com/seraphile/CMT/master/docs/moistfans.png
search_enabled: false
has_toc: true
