remote_theme: pmarsceill/just-the-docs
title: Canada Moist Talkers
description: Talk Spit, Get Hits. Logo by @longhairQ
logo: https://www.blaseball.wiki/images/thumb/a/a0/MoistTalkerLogo.png/480px-MoistTalkerLogo.png
search_enabled: false
